version: "2"
services:
  postgresql:
    image: postgres:16.0
    container_name: postgres_holi_java
    restart: always
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USE: postgres
      POSTGRES_DB: holi_java
