spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/holi_java
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always
  servlet:
    context-path: /api

